= 用例
:toc: manual

== AS 3 下发 VS 和 Cookie 会话保持

=== 目的

验证 AS 3 下发 VS 和 Cookie 会话保持。

=== 步骤

[source, bash]
.*1. 创建 App*
----
// deploymnets
kubectl create deployment app --image='registry.example.com:5443/backend:0.0.2'
kubectl scale deployments app --replicas=3 

// service
kubectl expose deployment app --port=80 --target-port=8080 --type=NodePort --name=app-svc
kubectl label svc app-svc cis.f5.com/as3-tenant=default
kubectl label svc app-svc cis.f5.com/as3-app=default_app
kubectl label svc app-svc cis.f5.com/as3-pool=app_svc_pool
----

[source, bash]
.*2. ConfigMap*
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "app_svc_test_001",
        "label": "default",
        "remark": "HTTP application",
        "default": {
          "class": "Tenant",
          "default_app": {
            "class": "Application",
            "template": "generic",
            "app_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "10.1.10.60"
              ],
              "virtualPort": 80,
              "pool": "app_svc_pool"
            },
            "app_svc_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }
----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== BIG-IP Controller 下发 iRules 的配置到 VE

=== 目的

BIG-IP Controller可以自动推送iRules及配置该iRules的VS的配置，添加应用及相关节点。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== BIG-IP Controller 下发 Policy 的配置到 VE

=== 目的

BIG-IP Controller可以自动推送Policy及配置该Policy的VS的配置，添加应用及相关节点。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== BIG-IP Controller 下发 SNAT 配置到 VE

=== 目的

BIG-IP Controller 可以自动推送 SNAT 的配置到 VE，能够自动为 VS 添加 snat pool。

=== 步骤    

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== BIG-IP Controller下发特定 namespace 的配置到 VE

=== 目的

BIG-IP Controller 监控特定的 namespace，BIG-IP Controller 只下发其监控特定的 namespace 里面配置的配置。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== 业务链健康检查

=== 目的

验证当 Pod 全部 down 后，VE和LTM 是否能够正确反馈结果。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== 通过 REST 下发负载均衡配置到 LTM

=== 目的

验证 F5 通过 REST 接口下发负载均衡配置到 LTM 的能力。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== 通过 REST 下发 monitor 到 LTM

=== 目的

验证F5通过REST接口下发monitor配置到LTM的能力。

===  步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== 通过 REST 下发 iRules 到 LTM

=== 目的

验证 F5 通过 REST 接口下发 iRules 配置到 LTM 的能力。

===  步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== BIG-IP Controller 和 prometheus 配合

=== 目的

验证 BIG-IP Controller 和 prometheus 的配合能力，使得 prometheus 能够读取 F5 的运行数据。

=== 步骤   

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== 通过 HSL 发送日志到 ELK

=== 目的

验证F5和ELK的结合能力。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== BIG-IP Controller 高可用

=== 目的

BIG-IP Controller 接受 K8s 管理，当 BIG-IP Controller 故障，K8s 会自动重新拉起一个 BIG-IP Controller，对此进行验证。

=== 步骤    

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== VE HA 高可用测试

=== 目的

验证 F5 VE 主备双机的切换能力。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

== VMware 自动拉起 VE 测试

=== 目的

测试验证 VMware 和 VE 的配合，验证当VE故障时，VMware 是否可以自动拉起新的VE。

=== 步骤

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----

[source, bash]
.**
----

----
