= OneConnect
:toc: manual

== 什么是 OneConnect？

OneConnect 通过更有效的利用 BIG-IP 和后台 pool members 之间创建的连接来提升网络的吞吐量。OneConnect 需要同 HTTP Keep-Alives 一起工作，通过重用服务端已存在的连接来实现降低服务端 TCP 连接总数，提高网络吞吐量的效果。

== 快速开始示例

[source, bash]
.*1. 创建 VS*
----
create ltm pool http_pool members add { 10.1.20.11:8081 { address 10.1.20.11 } 10.1.20.12:8081 { address 10.1.20.12 } }
create ltm profile one-connect custom_one_connect defaults-from oneconnect max-size 3 max-age 60 max-reuse 5 idle-timeout-override 30 source-mask 255.255.255.0 limit-type idle
create ltm virtual http_vs destination 10.1.10.20:80 ip-protocol tcp profiles add { http} pool http_pool profiles add { custom_one_connect }
----

[source, bash]
.*2. 关联 Debug Rules*
----
when HTTP_REQUEST_RELEASE {
  log local0. "BIG-IP: [IP::local_addr]:[TCP::local_port] sent [HTTP::method] to [IP::server_addr]:[serverside {TCP::remote_port}]"
}
----

[source, bash]
.*3. 在 Chrome 浏览器访问如下链接三次*
----
http://10.1.10.20/hello
----

[source, bash]
.*4. 查看日志输出*
----
Jul 28 10:22:43 bigip info tmm[16972]: Rule /Common/OneConnectTest <HTTP_REQUEST_RELEASE>: BIG-IP: 10.1.10.1:35709 sent GET to 10.1.20.11:8081
Jul 28 10:22:44 bigip info tmm[16972]: Rule /Common/OneConnectTest <HTTP_REQUEST_RELEASE>: BIG-IP: 10.1.10.1:35709 sent GET to 10.1.20.12:8081
Jul 28 10:22:45 bigip info tmm[16972]: Rule /Common/OneConnectTest <HTTP_REQUEST_RELEASE>: BIG-IP: 10.1.10.1:35711 sent GET to 10.1.20.11:8081
----

[source, bash]
.*5. 查看统计数据*
----
show ltm profile one-connect custom_one_connect
----


== OneConnect

* 全代理架构下，实现连接聚合降低服务器的连接总数，将服务器端的连接重复使用，以达到增加服务器出了能力的作用，可以增加 30% 的服务器处理能力
* 需要对每一个请求都进行单独处理（注意在多数情况下，LTM只对一个连接的第一个包进行处理）
* 典型的，打开Cookie会话保持有时候会出现保持不正确的情况，这时就需要打开One Connect
* 通过设置Mask=255.255.255.255，可以使后台服务器可以“看到”客户端源IP，但这个时候One-connect只对一个客户端的连接起作用

NOTE: One Connect Profile不是必须和HTTP Profile共用，也可以用于其他应用协议。用于其他应用协议的时候必须使用 iRules 编程来调用 One Connect。在需要对长连接进行拆分处理的时候，也需要用One Connect Profile。

[source, bash]
.*示例*
----
// 1. set up vs and pool
create ltm pool http_pool members add { 10.1.20.11:8081 { address 10.1.20.11 } 10.1.20.12:8081 { address 10.1.20.12 } }
create ltm profile one-connect custom_one_connect defaults-from oneconnect max-size 3 max-age 60 max-reuse 5 idle-timeout-override 30 source-mask 255.255.255.0 limit-type idle
create ltm virtual http_vs destination 10.1.10.20:80 ip-protocol tcp profiles add { http} pool http_pool profiles add { custom_one_connect }


create ltm pool http_pool members add { 10.1.20.11:8081 { address 10.1.20.11 } 10.1.20.12:8081 { address 10.1.20.12 } 10.1.20.13:8081 { address 10.1.20.13 } }
create ltm virtual http_vs destination 10.1.10.20:80 ip-protocol tcp pool http_pool

// 2. create OneConnect profie and reference to VS
create ltm profile one-connect custom_one_connect defaults-from oneconnect max-size 200 max-age 60 idle-timeout-override 30 source-mask 255.255.255.0 limit-type idle
modify ltm virtual http_vs profiles add { custom_one_connect { } }

// 3. test, send 100 times http request
for i in {1..100} ; do curl http://10.1.10.20/hello; sleep 0.1; done

// 4. check the connection pool 
# show sys connection cs-server-addr 10.1.10.20
Sys::Connections
10.1.10.1:60789  10.1.10.20:80  any6.any  any6.any  tcp  2  (tmm: 1)  none  none
10.1.10.1:60797  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 1)  none  none
10.1.10.1:60794  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 1)  none  none
10.1.10.1:60793  10.1.10.20:80  any6.any  any6.any  tcp  2  (tmm: 1)  none  none
10.1.10.1:60801  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 1)  none  none
10.1.10.1:60802  10.1.10.20:80  any6.any  any6.any  tcp  0  (tmm: 1)  none  none
10.1.10.1:60798  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 1)  none  none
10.1.10.1:60790  10.1.10.20:80  any6.any  any6.any  tcp  2  (tmm: 1)  none  none
10.1.10.1:60799  10.1.10.20:80  any6.any  any6.any  tcp  0  (tmm: 0)  none  none
10.1.10.1:60787  10.1.10.20:80  any6.any  any6.any  tcp  2  (tmm: 0)  none  none
10.1.10.1:60803  10.1.10.20:80  any6.any  any6.any  tcp  0  (tmm: 0)  none  none
10.1.10.1:60791  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 0)  none  none
10.1.10.1:60796  10.1.10.20:80  any6.any  any6.any  tcp  0  (tmm: 0)  none  none
10.1.10.1:60788  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 0)  none  none
10.1.10.1:60792  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 0)  none  none
10.1.10.1:60795  10.1.10.20:80  any6.any  any6.any  tcp  1  (tmm: 0)  none  none
10.1.10.1:60800  10.1.10.20:80  any6.any  any6.any  tcp  0  (tmm: 0)  none  none
Total records returned: 17

// 5. clean up
delete ltm virtual http_vs
delete ltm pool http_pool
delete ltm profile one-connect custom_one_connect 
----

== 注意事项

* OneConnect 通常需要同 HTTP Profile 一起使用
* 不建议通过 OneConnect 处理 FTP 或 RTSP
* 应避免 OneConnect 使用在服务器端是加密的场景，如果是加密场景可先在 F5 上进行卸载。 
