= Q & A
:toc: manual

== Quick Link

* Displaying the BIG-IP software version - https://support.f5.com/csp/article/K8759
* BIG-IP DNS synchronization group requirements - https://support.f5.com/csp/article/K13734
* Overview of DNS query processing on BIG-IP systems - https://support.f5.com/csp/article/K14510

== Networking

1. In routed mode, due to the full proxy architecture, there should be a connection between BIG-IP and backend server, why check from backend server, the source is Client, rather than Big-IP(`10.1.20.12:8081         10.1.10.199:10177`)?
2. Still in routed mode, the full proxy, there are 2 connections(Client to BIG-IP, BIG-IP to Server), how the infors exchanged between these two connections? 
3. Why external gateway can be used to access the Configure Utility UI? 
4. Is VE/BIG-IP default only allow 3 network(mgmt, external, internal)? check from both tmsh and from linux, there only 3 interface defined.
5. 关于内网访问外网，使用 NAT 可以配置通吗(NAT 的原理是将内网地址(originating-address) 映射到外网(translation-address)，从文档看到 NAT 可以是双向的，但我没有配通，SNAT 可以通)？

== VS & Load Balancer

1. 最常用的 VS Type 是 Standard？其他类型客户使用多吗？What's the purpose of *Performance(Layer 4)*, client protocal fastL4? also if select fastL4 the cookie persistence not take effect? the tmsh cli create vs default is fastL4(if do not append with ip-protocol tcp).
2. 那个负载均衡策略使用的比较多？动态负载均衡策略安全吗（因为安装插件，从三方监控平台获取服务器指标数据）？

== Profiles

1. Why the `ui.statistics.modulestatistics.localtraffic.persistencerecords` default is false?
2. Is there a DB used to persist large volume of persistence records?
3. 客户真实使用中，对 TCP 加速相关的 Profile 使用广泛吗(tcp-lan-optimized, tcp-wan-optimized)？
4. Why OneConnect profile depend on web-acceleration profile(it seems optimized-acceleration enabled reuse the server side connection)? 
5. Is there any benefit for using Stream Profile with HTTP Compression Profile(Stream Profile can work without http compression profile)?  
6. Does HTTP Compression depend on web-acceleration profile(Is http compresstion made data transfer from client to BIG-IP and BIG-IP to server small?)?
7. Does web-acceleration profile related with HTTP Compression?

== Other

1. BIG-IP 高可用有没有一个盒子里两套软件做两个点当一个点不可用，切换到另一个点？（之前听说的）
2. What the means of 1SLOT(BIGIP-14.1.2.3-0.0.5.ALL_1SLOT-vmware.ova) flag means in VE download file? what's the difference bewteen BIGIP-14.1.2.3-0.0.5.ALL_1SLOT-vmware.ova and BIGIP-14.1.2.3-0.0.5.ALL-vmware.ova?


